branch-defaults:
  master:
    environment: null
global:
  application_name: multi-docker
  branch: master
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-east-2
  sc: git