version: 2.1
jobs:
  pre_build:
    working_directory: ~/dockerAndKubernetesTheCompleteGuide/complex
    docker:
      - image: circleci/node:lts
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    steps:
      - checkout:
          path: ~/dockerAndKubernetesTheCompleteGuide
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build client for testing
          command: |
            docker build -t $DOCKER_USER/complex-client-test -f ./client/Dockerfile.dev ./client
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push $DOCKER_USER/complex-client-test
  test:
    docker:
      - image: circleci/node:lts
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Execute tests
          command: docker run -e CI=true $DOCKER_USER/complex-client-test npm run test
  build:
    working_directory: ~/dockerAndKubernetesTheCompleteGuide/complex
    docker:
      - image: circleci/node:lts
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    steps:
      - checkout:
          path: ~/dockerAndKubernetesTheCompleteGuide
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build client
          command: |
            docker build -t $DOCKER_USER/complex-client ./client
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push $DOCKER_USER/complex-client
      - run:
          name: Build nginx
          command: |
            docker build -t $DOCKER_USER/complex-nginx ./nginx
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push $DOCKER_USER/complex-nginx
      - run:
          name: Build server
          command: |
            docker build -t $DOCKER_USER/complex-server ./server
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push $DOCKER_USER/complex-server
      - run:
          name: Build worker
          command: |
            docker build -t $DOCKER_USER/complex-worker ./worker
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push $DOCKER_USER/complex-worker
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    working_directory: ~/dockerAndKubernetesTheCompleteGuide/complex
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout:
          path: ~/dockerAndKubernetesTheCompleteGuide
      - run:
          name: Install AWS CLI 
          command: sudo pip install awsebcli
      - run:
          name: Create AWS credential
          command: |
            chmod +x ./setup-eb.sh
            bash ./setup-eb.sh 
      - run:
          name: Deploy to EB if branch is master
          command: |
            eb use DockerReact-env
            eb deploy

workflows:
  build_test_deploy:
    jobs:
      - pre_build
      - test:
          requires:
            - pre_build
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master