version: 2.1
jobs:
  build:
    working_directory: ~/dockerAndKubernetesTheCompleteGuide/frontend
    docker:
      - image: circleci/node:lts
    steps:
      - checkout:
          path: ~/dockerAndKubernetesTheCompleteGuide
      - run:
          name: Install dependencies
          command: npm install
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    docker:
      - image: circleci/node:lts
    steps:
      - attach_workspace:
          at: .
      - run: 
          name: Execute tests
          command: npm run test
  deploy:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout:
          path: ~/dockerAndKubernetesTheCompleteGuide
      - run:
          name: Install AWS CLI 
          command: |
            sudo pip install awsebcli --upgrade --user
      - run:
          name: Create AWS credentials manually
          command: |
            mkdir ~/.aws
            touch ~/.aws/config
            chmod 600 ~/.aws/config 
            echo "aws_region=$REGION" >> ~/.aws/config
            echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/config
            echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/config
      - run:
          name: Deploy to EB if branch is master
          command: |
            eb use DockerReact-env
            eb deploy

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master