version: 2.1
jobs:
  build:
    working_directory: ~/dockerAndKubernetesTheCompleteGuide/frontend
    docker:
      - image: circleci/node:lts
        auth:
          username: cindyledev
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout:
          path: ~/dockerAndKubernetesTheCompleteGuide
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build frontend
          command: | 
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t cindyledev/docker-frontend -f Dockerfile.dev .
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push cindyledev/docker-frontend:$TAG
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    docker:
      - image: circleci/node:lts
        auth:
          username: cindyledev
          password: $DOCKERHUB_PASSWORD
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker:
          version: 19.03.13
      - run: 
          name: Execute tests
          command: docker run cindyledev/docker-frontend npm run test -- -- coverage
  deploy:
    working_directory: ~/dockerAndKubernetesTheCompleteGuide/frontend
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout:
          path: ~/dockerAndKubernetesTheCompleteGuide
      - run:
          name: Install AWS CLI 
          command: sudo pip install awsebcli
      - run:
          name: Create AWS credential
          command: |
            chmod +x ./setup-eb.sh
            bash ./setup-eb.sh
      - run:
          name: Deploy to EB if branch is master
          command: |
            eb use DockerReact-env
            eb deploy

workflows:
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master