version: 2.1
jobs:
  build_worker:
    working_directory: ~/dockerAndKubernetesTheCompleteGuide/complex/worker
    docker:
      - image: circleci/node:lts
    steps:
      - checkout:
          path: ~/dockerAndKubernetesTheCompleteGuide
      - run:
          name: Install dependencies
          command: npm install
      - persist_to_workspace:
          root: .
          paths:
            - .
  build_server:
    working_directory: ~/dockerAndKubernetesTheCompleteGuide/complex/server 
    docker: 
      - image: circleci/node:lts
    steps:
      - checkout:
          path: ~/dockerAndKubernetesTheCompleteGuide
      - run:
          name: Install dependencies
          command: npm install
      - persist_to_workspace:
          root: .
          paths:
            - .
  build_client:
    working_directory: ~/dockerAndKubernetesTheCompleteGuide/complex/client 
    docker:
      - image: circleci/node:lts
    steps:
      - checkout:
          path: ~/dockerAndKubernetesTheCompleteGuide
      - run:
          name: Install dependencies
          command: npm install
      - persist_to_workspace:
          root: .
          paths:
            - .
  test_client:
    docker:
      - image: circleci/node:lts
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Execute tests
          command: npm run test

workflows:
  build_and_test:
    jobs:
      - build_worker
      - build_server
      - build_client
      - test_client:
          requires:
            - build_client