version: 2.1
jobs:
  build:
    working_directory: ~/dockerAndKubernetesTheCompleteGuide/frontend
    docker:
      - image: circleci/node:lts
    steps:
      - checkout:
          path: ~/dockerAndKubernetesTheCompleteGuide
      - run:
          name: Install dependencies
          command: npm install
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    docker:
      - image: circleci/node:lts
    steps:
      - attach_workspace:
          at: .
      - run: 
          name: Execute tests
          command: npm run test
  deploy:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout:
          path: ~/dockerAndKubernetesTheCompleteGuide
      - run:
          name: build
          command: npm run build

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build